```{r}
library(rvest)
library(dplyr)
library(pipeR)
library(knitr)
```

```{r}
contract_url <- "https://widgets.sports-reference.com/wg.fcgi?css=1&site=bbr&url=%2Fcontracts%2F"

contract_table <- function(team){
  url <- paste0(contract_url,team,".html&div=div_contracts")
  table <- htmltab(url)
  return(table)
}

```

```{r}
pgs_url <- "https://widgets.sports-reference.com/wg.fcgi?css=1&site=bbr&url=%2Fplayoffs%2FNBA_"

pgs_table <- function(year){
  url <- paste0(pgs_url,year,".html&div=div_team-stats-per_game")
  table <- htmltab(url)
  return(table)
}

playoffs2017pgs <- htmltab("https://widgets.sports-reference.com/wg.fcgi?css=1&site=bbr&url=%2Fplayoffs%2FNBA_2017.html&div=div_team-stats-per_game")
```

```{r}
caphistory <- htmltab("https://widgets.sports-reference.com/wg.fcgi?css=1&site=bbr&url=%2Fcontracts%2Fsalary-cap-history.html&div=div_salary_cap_history")
```

```{r}
shoot_url <- "https://widgets.sports-reference.com/wg.fcgi?css=1&site=bbr&url=%2Fplayoffs%2FNBA_"

shoot_table <- function(year){
  url <- paste0(shoot_url,year,".html&div=div_team_shooting")
  table <- htmltab(url)
  return(table)
}

playoffs2017shooting <- htmltab("https://widgets.sports-reference.com/wg.fcgi?css=1&site=bbr&url=%2Fplayoffs%2FNBA_2017.html&div=div_team_shooting")
```


```{r}
team_url <- "https://widgets.sports-reference.com/wg.fcgi?css=1&site=bbr&url=%2Fteams%2F"
caphistoryurl <- "https://widgets.sports-reference.com/wg.fcgi?css=1&site=bbr&url=%2Fcontracts%2Fsalary-cap-history.html&div=div_salary_cap_history"
contract_url <- "https://widgets.sports-reference.com/wg.fcgi?css=1&site=bbr&url=%2Fcontracts%2F"
playoffs_url<-"https://widgets.sports-reference.com/wg.fcgi?css=1&site=bbr&url=%2Fplayoffs%2FNBA_"

get.team <- function(team, year, element){
  if (element == "roster") {
    urltable <- paste0(team_url, team,"%2F", year, ".html&div=div_", element)
    table <- htmltab(urltable) %>% 
    mutate(Team = team) %>% 
    rename(Nationality = V1) 
  } else if ((element == "per_game") || (element == "salaries2")) {
      urltable <- paste0(team_url, team,"%2F", year, ".html&div=div_", element)
      table <- htmltab(urltable) %>% 
      mutate(Team = team) %>% 
      rename(Player = V1)
      table <- table[,-1]
  } else if (element == "contracts") {
      urltable <- paste0(contract_url,team,".html&div=div_contracts")
      table <- htmltab(urltable)
  } else if (element == "salary_cap_history") {
      table <- htmltab("https://widgets.sports-reference.com/wg.fcgi?css=1&site=bbr&url=%2Fcontracts%2Fsalary-cap-history.html&div=div_salary_cap_history")
  }
    else {
      urltable <- paste0(team_url, team,"%2F", year, ".html&div=div_", element)
      table <- htmltab(urltable) %>% 
      mutate(Team = team) %>% 
      within(rm(Rk))
  }
  return(table)
}

test <- get.team("CLE", "2015", "contracts")
head(test)
```

```{r}
playoffs_url<-"https://widgets.sports-reference.com/wg.fcgi?css=1&site=bbr&url=%2Fplayoffs%2FNBA_"

get.playoffs <- function(year, type, table) {
  if (type == "games") {
    urltable <- paste0(playoffs_url, year, "_", type, ".html&div=div_", table)
    table <- htmltab(urltable)
    names(table)[names(table) == "Visitor/Neutral"] <- "Away"
    names(table)[names(table) == "Home/Neutral"] <- "Home"
    names(table)[names(table) == "PTS"] <- "PTS Away"
    names(table)[names(table) == "PTS.1"] <- "PTS Home"
    table <- table[,-7]
  } else if ((type == "per_game") || (type == "advanced")) {
    urltable <- paste0(playoffs_url, year, "_", type, ".html&div=div_", table)
    table <- htmltab(urltable)
    table <- table[,-1]
  } else {
    urltable <- paste0(playoffs_url,year,".html&div=div_", table)
    table <- htmltab(urltable)
    table <- table[,-1]
  }
  return(table)
}

test1 <- get.playoffs("2017", "games", "schedule")
```

```{r}
playoffs_url<-"https://widgets.sports-reference.com/wg.fcgi?css=1&site=bbr&url=%2Fplayoffs%2FNBA_"

get.playoffs <- function(year, type, table) {
  if (type == "games") {
    urltable <- paste0(playoffs_url, year, "_", type, ".html&div=div_", table)
    urltibble <- as.tibble(urltable)
    temp.text <- urltibble[104,]
    table <- htmltab(temp.text[[1]], which =1 )
    names(table)[names(table) == "Visitor/Neutral"] <- "Away"
    names(table)[names(table) == "Home/Neutral"] <- "Home"
    names(table)[names(table) == "PTS"] <- "PTS Away"
    names(table)[names(table) == "PTS.1"] <- "PTS Home"
    table <- table[,-7]
  } else if ((type == "per_game") || (type == "advanced")) {
    urltable <- paste0(playoffs_url, year, "_", type, ".html&div=div_", table)
    urltibble <- as.tibble(urltable)
    temp.text <- urltibble[104,]
    table <- htmltab(temp.text[[1]], which =1 )
    table <- htmltab(urltable)
    table <- table[,-1]
  } else {
    urltable <- paste0(playoffs_url,year,".html&div=div_", table)
    urltibble <- as.tibble(urltable)
    temp.text <- urltibble[104,]
    table <- htmltab(temp.text[[1]], which =1 )
    table <- htmltab(urltable)
    table <- table[,-1]
  }
  return(table)
}
```

```{r}
#Read the webpage which is just html code for the widget
thepage <-  readLines('https://widgets.sports-reference.com/wg.fcgi?css=1&site=bbr&url=%2Fteams%2FBOS%2F2018.html&div=div_advanced')

#Convert the webpage into an easily subsettable tibble
thepage.tib <- as.tibble(thepage) 

#Find the row including the data table
temp.text <- thepage.tib[104,] #This stores as a list

#Read the html code as a data table
AdvancedPBP <- htmltab(temp.text[[1]], which =1 ) #Call the data table element in the list 

#Format the data table
AdvancedPBP <- AdvancedPBP %>% 
  mutate(Team = "BOS") %>% 
  rename(Player = V1) %>% 
  dplyr::select(-Rk)

head(AdvancedPBP)

```

```{r}
playoffs_url<-"https://widgets.sports-reference.com/wg.fcgi?css=1&site=bbr&url=%2Fplayoffs%2FNBA_"

get.playoffs <- function(year, type, table) {
  if (type == "games") {
    urltable <- paste0(playoffs_url, year, "_", type, ".html&div=div_", table)
    playoffspage <- readLines(urltable)
    playoffs.tib <- as.tibble(playoffspage)
    temp.text <- playoffs.tib[104,] #This stores as a list
    table <- htmltab(temp.text[[1]], which =1, rm_nodata_cols = F)
    names(table)[names(table) == "Visitor/Neutral"] <- "Away"
    names(table)[names(table) == "Home/Neutral"] <- "Home"
    names(table)[4] <- "PTS AWAY"
    names(table)[6] <- "PTS HOME"
    table <- table[,-7:-9]
  } else if ((type == "per_game") || (type == "advanced")) {
    urltable <- paste0(playoffs_url, year, "_", type, ".html&div=div_", table)
    playoffspage <- readLines(urltable)
    playoffs.tib <- as.tibble(playoffspage)
    temp.text <- playoffs.tib[104,] #This stores as a list
    table <- htmltab(temp.text[[1]], which =1, rm_nodata_cols = F)
    table <- table %>% select(-Rk) %>% filter(Player != "Player")
  } else {
    urltable <- paste0(playoffs_url,year,".html&div=div_", table)
    playoffspage <- readLines(urltable)
    playoffs.tib <- as.tibble(playoffspage)
    temp.text <- playoffs.tib[104,] #This stores as a list
    table <- htmltab(temp.text[[1]], which =1, rm_nodata_cols = F)
  }
  return(table)
}

```

```{r}

year.vect <- c("2018" ,"2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008")

OverTime <- function(variable){
  df.out <- as.tibble()
  for(i in 1:10){
  Season <- get.season(year.vect[i], "team-stats-per_game") %>%
    mutate(Varss = as.numeric(as.character(variable))) %>%
    summarise(Avg = mean(Varss)) %>%
    mutate(Year = year.vect[i])
  df.out <- bind_rows(df.out, Season)
  }
  
return(df.out)
}

OverTime("PTS")

Season <- get.season("2018", "team-stats-per_game") %>%
    mutate(Varss = as.numeric(as.character(PTS))) %>%
    summarise(Avg = mean(Varss, na.rm = T))
```

```{r}
get.team("BOS", "2017", "team-stats-per_game")

```
