---
title: "Joining Odds Data"
author: "Derrick Yam"
date: "December 6, 2017"
output: html_document
---

##Libraries
```{r}
library(lubridate)
library(dplyr)

```

##Load the data after the names were edited in Excel
```{r}
NBAOdds <- read.csv("NBAOdds20072018.csv") 
```

##Format the data frame so that it easily joins with the data webscraped.

```{r}
head(NBAOdds)
NBAOdds <- NBAOdds %>% 
  select(-X) %>% 
  mutate(Date = mdy(Date))

NBAOdds <- NBAOdds %>% 
  rename(PTSH = HFinal,
         PTSV = VFinal,
         Visitor = Away)

#NBAOdds <- NBAOdds[, c(1, 3, 2, )]
head(NBAOdds)
str(NBAOdds)
write.csv(NBAOdds, "NBAOdds20072018Update.csv")
```

```{r}
schedule_url<-"https://widgets.sports-reference.com/wg.fcgi?css=1&site=bbr&url=%2Fleagues%2FNBA_"
standing_url<-"https://www.basketball-reference.com/leagues/NBA_"
opgs_url<-"https://widgets.sports-reference.com/wg.fcgi?css=1&site=bbr&url=%2Fplayoffs%2FNBA_"
ops_url<-"https://widgets.sports-reference.com/wg.fcgi?css=1&site=bbr&url=%2Fplayoffs%2FNBA_"

#schedule
schedule_table<-function(year){
  month=c("october","november","december","january","february",
          "march","april","may","june")
  result=NA
  for(a in 1:9){
    url<-paste0(schedule_url,year,"_games-",month[a],".html&div=div_schedule")
    table<-htmltab(url)
    result=rbind(result,table)}
  result<-result %>% 
    drop_na() %>%
    filter(Date !="Playoffs")
  names(result)[3]<-"Visitor"
  names(result)[4]<-"PTSH"
  names(result)[5]<-"Home"
  names(result)[6]<-"PTSV"
  result$Date<-as.Date(result$Date, '%a, %b %d, %Y')
  return(result)
}

schedule_2017<-schedule_table(2017)
head(schedule_2017)

```
