---
title: "Webscraping Live Betting Odds"
author: "Derrick Yam"
date: "December 6, 2017"
output: html_document
---

##Load Libraries
```{r}
library(rvest)
library(pipeR)
library(knitr)
library(xml2)
library(htmltab)
library(readxl)
library(tidyr)
library(lubridate)
library(dplyr)
library(stringr)
library(stringi)
library(rebus)
library(tibble)
options(tibble.width = Inf)
```


##Live Webscraping Function
```{r}
DailyOdds <- function(Date = "20171206"){
  if(ymd(Date) > today() +1) {
    print("Sorry, the betting lines are not set yet! Lines are only released for today and the following day. Check back again!")
  } else {
##Spreads Tables
url.spread <- paste0("http://www.donbest.com/nba/odds/spreads/", Date, ".html")

SpreadsTable <- url.spread %>%
    read_html %>%
    html_nodes(xpath = '//*[@id="oddsHolder"]/div[1]/table') %>%
    html_table(header = F, fill =T) %>%
    data.frame() %>%
    tbl_df()

SpreadsTable <- SpreadsTable[-1, ]

names(SpreadsTable) <- SpreadsTable[1,]
SpreadsTable <- SpreadsTable[-1, ]

SpreadsTable <- SpreadsTable %>% 
  select(Rot, Opener, Team, Time, Bovada, Pinnacle, Mirage)

#Rot works
SpreadsTable <- SpreadsTable %>% 
  mutate(Rot1 = as.character(Rot),
         Rot2 = as.character(Rot))

SpreadsTable$Rot1 <- str_sub(SpreadsTable$Rot1, 1, 3)
SpreadsTable$Rot2 <- str_sub(SpreadsTable$Rot2, 4, 6)

#We need to create a regex pattern
SpreadsTable <- SpreadsTable %>% 
  mutate(OS = Opener)

#Opening Spread
pattern <- str_c("[+-]", "[:digit:]+", ".?", "[:digit:]*","[\\s]")
SpreadsTable$OSAway <- str_match(SpreadsTable$OS, pattern)
SpreadsTable$OSAway <- sub("\\s+", "", SpreadsTable$OSAway)

SpreadsTable$Bovada <- str_match(SpreadsTable$Bovada, pattern)
SpreadsTable$Bovada <- sub("\\s+", "", SpreadsTable$Bovada)

SpreadsTable$Pinnacle <- str_match(SpreadsTable$Pinnacle, pattern)
SpreadsTable$Pinnacle <- sub("\\s+", "", SpreadsTable$Pinnacle)

SpreadsTable$Mirage <- str_match(SpreadsTable$Mirage, pattern)
SpreadsTable$Mirage <- sub("\\s+", "", SpreadsTable$Mirage)

#Teams

#Team Away City
patternteam <- str_c("((^[:upper:][:lower:]+)[:blank:][:upper:][:lower:]+[:blank:])|((^[:upper:][:lower:]+)[:blank:])")
SpreadsTable$TeamAwayCity <- str_match(SpreadsTable$Team, patternteam)
SpreadsTable$Team <- str_replace(SpreadsTable$Team, patternteam, "")

#Team Away
patternteam2 <- str_c("(^[:upper:][:lower:]+|76ers)")
SpreadsTable$TeamAway <- str_match(SpreadsTable$Team, patternteam2)
SpreadsTable$Team <- str_replace(SpreadsTable$Team, patternteam2, "")

#Put the city and nickname together
SpreadsTable <- as.data.frame(SpreadsTable)
SpreadsTable$Bovada <- SpreadsTable$Bovada[,1]
SpreadsTable$Mirage <- SpreadsTable$Mirage[,1]
SpreadsTable$Pinnacle <- SpreadsTable$Pinnacle[,1]
SpreadsTable$OSAway <- SpreadsTable$OSAway[,1]
SpreadsTable$TeamAwayCity <- SpreadsTable$TeamAwayCity[,1]
SpreadsTable$TeamAway <- SpreadsTable$TeamAway[,1]

SpreadsTable <- SpreadsTable %>% 
  mutate(Away = paste0(TeamAwayCity, TeamAway))

SpreadsTable <- SpreadsTable %>% 
  select(Team, Time, Bovada, Pinnacle, Mirage, Rot1, Rot2, OSAway, Away) %>% 
  dplyr::rename(Home = Team, RotAway = Rot1, RotHome = Rot2)

#MoneyLine Table
url.ML <- paste0("http://www.donbest.com/nba/odds/money-lines/", Date, ".html")

MoneyLineTable <- url.ML %>%
    read_html %>%
    html_nodes(xpath = '//*[@id="oddsHolder"]/div[1]/table') %>%
    html_table(header = F, fill =T) %>%
    data.frame() %>%
    tbl_df()

MoneyLineTable <- MoneyLineTable[-1, ]

names(MoneyLineTable) <- MoneyLineTable[1,]
MoneyLineTable <- MoneyLineTable[-1, ]

MoneyLineTable <- MoneyLineTable %>% 
  select(Rot, Opener, Team, Time, Bovada, Pinnacle, Mirage)

#Rot works
MoneyLineTable <- MoneyLineTable %>% 
  mutate(Rot1 = as.character(Rot),
         Rot2 = as.character(Rot))

MoneyLineTable$Rot1 <- str_sub(MoneyLineTable$Rot1, 1, 3)
MoneyLineTable$Rot2 <- str_sub(MoneyLineTable$Rot2, 4, 6)

#Money Line Away
pattern <- str_c("^[+-]", "[:digit:]+")
MoneyLineTable$OpenerAwayML <- str_match(MoneyLineTable$Opener, pattern)
MoneyLineTable$BovadaAwayML <- str_match(MoneyLineTable$Bovada, pattern)
MoneyLineTable$PinnacleAwayML <- str_match(MoneyLineTable$Pinnacle, pattern)
MoneyLineTable$MirageAwayML <- str_match(MoneyLineTable$Mirage, pattern)

#Money Line Home
pattern <- str_c("[+-]", "[:digit:]+$")
MoneyLineTable$OpenerHomeML <- str_match(MoneyLineTable$Opener, pattern)
MoneyLineTable$BovadaHomeML <- str_match(MoneyLineTable$Bovada, pattern)
MoneyLineTable$PinnacleHomeML <- str_match(MoneyLineTable$Pinnacle, pattern)
MoneyLineTable$MirageHomeML <- str_match(MoneyLineTable$Mirage, pattern)

#Teams
#Team Away City
patternteam <- str_c("((^[:upper:][:lower:]+)[:blank:][:upper:][:lower:]+[:blank:])|((^[:upper:][:lower:]+)[:blank:])")
MoneyLineTable$TeamAwayCity <- str_match(MoneyLineTable$Team, patternteam)
MoneyLineTable$Team <- str_replace(MoneyLineTable$Team, patternteam, "")

#Team Away
patternteam2 <- str_c("(^[:upper:][:lower:]+|76ers)")
MoneyLineTable$TeamAway <- str_match(MoneyLineTable$Team, patternteam2)
MoneyLineTable$Team <- str_replace(MoneyLineTable$Team, patternteam2, "")

#Put the city and nickname together
MoneyLineTable <- as.data.frame(MoneyLineTable)

#Weird Structure

MoneyLineTable$BovadaAwayML <- MoneyLineTable$BovadaAwayML[,1]
MoneyLineTable$MirageAwayML <- MoneyLineTable$MirageAwayML[,1]
MoneyLineTable$PinnacleAwayML <- MoneyLineTable$PinnacleAwayML[,1]
MoneyLineTable$OpenerAwayML <- MoneyLineTable$OpenerAwayML[,1]
MoneyLineTable$OpenerHomeML <- MoneyLineTable$OpenerHomeML[,1]
MoneyLineTable$PinnacleHomeML <- MoneyLineTable$PinnacleHomeML[,1]
MoneyLineTable$MirageHomeML <- MoneyLineTable$MirageHomeML[,1]
MoneyLineTable$BovadaHomeML <- MoneyLineTable$BovadaHomeML[,1]

#Team 
MoneyLineTable$TeamAwayCity <- MoneyLineTable$TeamAwayCity[,1]
MoneyLineTable$TeamAway <- MoneyLineTable$TeamAway[,1]

MoneyLineTable <- MoneyLineTable %>% 
  mutate(Away = paste0(TeamAwayCity, TeamAway))

MoneyLineTable <- MoneyLineTable %>% 
  select(-Rot, -Opener, -Bovada, - Pinnacle, - Mirage, - TeamAwayCity, -TeamAway) %>% 
  dplyr::rename(Home = Team, RotAway = Rot1, RotHome = Rot2)

url.OU <- paste0("http://www.donbest.com/nba/odds/totals/", Date, ".html")

OverUnderTable <- url.OU %>%
    read_html %>%
    html_nodes(xpath = '//*[@id="oddsHolder"]/div[1]/table') %>%
    html_table(header = F, fill =T) %>%
    data.frame() %>%
    tbl_df()

OverUnderTable <- OverUnderTable[-1, ]

names(OverUnderTable) <- OverUnderTable[1,]
OverUnderTable <- OverUnderTable[-1, ]

OverUnderTable <- OverUnderTable %>% 
  select(Rot, Opener, Team, Time, Bovada, Pinnacle, Mirage)

#Rot works
OverUnderTable <- OverUnderTable %>% 
  mutate(Rot1 = as.character(Rot),
         Rot2 = as.character(Rot))

OverUnderTable$Rot1 <- str_sub(OverUnderTable$Rot1, 1, 3)
OverUnderTable$Rot2 <- str_sub(OverUnderTable$Rot2, 4, 6)

#OverUnder
pattern <- str_c("[:digit:]{3}\\.[:digit:]")
OverUnderTable$OpenerOU <- str_match(OverUnderTable$Opener, pattern)
OverUnderTable$BovadaOU <- str_match(OverUnderTable$Bovada, pattern)
OverUnderTable$PinnacleOU <- str_match(OverUnderTable$Pinnacle, pattern)
OverUnderTable$MirageOU <- str_match(OverUnderTable$Mirage, pattern)

#Teams
#Team Away City
patternteam <- str_c("((^[:upper:][:lower:]+)[:blank:][:upper:][:lower:]+[:blank:])|((^[:upper:][:lower:]+)[:blank:])")
OverUnderTable$TeamAwayCity <- str_match(OverUnderTable$Team, patternteam)
OverUnderTable$Team <- str_replace(OverUnderTable$Team, patternteam, "")

#Team Away
patternteam2 <- str_c("(^[:upper:][:lower:]+|76ers)")
OverUnderTable$TeamAway <- str_match(OverUnderTable$Team, patternteam2)
OverUnderTable$Team <- str_replace(OverUnderTable$Team, patternteam2, "")

#Put the city and nickname together
OverUnderTable <- as.data.frame(OverUnderTable)
#Weird Structure

OverUnderTable$BovadaOU <- OverUnderTable$BovadaOU[,1]
OverUnderTable$MirageOU <- OverUnderTable$MirageOU[,1]
OverUnderTable$PinnacleOU <- OverUnderTable$PinnacleOU[,1]
OverUnderTable$OpenerOU <- OverUnderTable$OpenerOU[,1]

#Team 
OverUnderTable$TeamAwayCity <- OverUnderTable$TeamAwayCity[,1]
OverUnderTable$TeamAway <- OverUnderTable$TeamAway[,1]

OverUnderTable <- OverUnderTable %>% 
  mutate(Away = paste0(TeamAwayCity, TeamAway))

OverUnderTable <- OverUnderTable %>% 
  select(-Rot, -Opener, -Bovada, - Pinnacle, - Mirage, - TeamAwayCity, -TeamAway) %>% 
  dplyr::rename(Home = Team, RotAway = Rot1, RotHome = Rot2)

BettingTable <- left_join(SpreadsTable, MoneyLineTable, by = c("Home", "Away", "Time", "RotAway", "RotHome")) %>% 
  left_join(OverUnderTable, by = c("Home", "Away", "Time", "RotAway", "RotHome"))

BettingTable <- BettingTable[, c(1, 9, 2:8, 10:21)] %>% 
  dplyr::rename(BovadaAwayS = Bovada,
         PinnacleAwayS = Pinnacle,
         MirageAwayS = Mirage,
         OpenerAwayS = OSAway)

BettingTable <- BettingTable %>% 
  mutate(Time = hm(Time))

for(i in 4:length(BettingTable)){
  BettingTable[,i] <- as.numeric(BettingTable[,i]) 
}

#Create a win probability from the Bovada money line
BettingTable <- BettingTable %>% 
  mutate(WP.HB = ifelse(PinnacleHomeML > 0, 100/(PinnacleHomeML + 100),
                       PinnacleHomeML/(PinnacleHomeML -100)),
         WP.VB = ifelse(PinnacleAwayML > 0, 100/(PinnacleAwayML + 100),
                       PinnacleAwayML/(PinnacleAwayML -100)),
         WP.H = (WP.HB + (1-WP.VB))/2,
         WP.V = 1 - WP.H)  %>% 
  select(-WP.HB, -WP.VB) %>% 
  mutate(Date = ymd(Date))
return(BettingTable)
  }
  
}

DailyOdds("20171212")

```

##Create a function to take individual team's schedules
```{r}
urltable <- "https://widgets.sports-reference.com/wg.fcgi?css=1&site=bbr&url=%2Fteams%2FBOS%2F2018_games.html&div=div_games"

 
##Work on a function with these lines after
funct.team.sched <- function(team){
  team <- paste(team)
  urltable <- paste0("https://widgets.sports-reference.com/wg.fcgi?css=1&site=bbr&url=%2Fteams%2F",
                     team, "%2F2018_games.html&div=div_games")
  thepage <-  readLines(urltable)
  #Convert the webpage into an easily subsettable tibble
  thepage.tib <- as.tibble(thepage) 
  #Find the row including the data table
  temp.text <- thepage.tib[104,] #This stores as a list
  #Read the html code as a data table
  schedule.team <- htmltab(temp.text[[1]], which =1, rm_nodata_cols = F) #Call the data table element in   the list 
  
  names(schedule.team)[3] <- "Time"
  names(schedule.team)[6] <- "Home"
  names(schedule.team)[8] <- "Result"
  names(schedule.team)[10] <- "TeamPoints"
  names(schedule.team)[11] <- "OppPoints"
  
  schedule.team <- schedule.team[, c(-1, -4, -5, -9, -15)] 
  
  teamname <- AbrevToName(team)
  schedule.team <- schedule.team %>% 
    mutate(Team = team)
  
  schedule.team <- schedule.team %>% 
    filter(Opponent != "Opponent") %>% 
    mutate(Date = as.Date(Date, '%a, %b %d, %Y'),
           Home = ifelse(is.na(Home), 1, 0))
  return(schedule.team)
}

funct.team.sched("BOS")
head(schedule.team)
  
```

##Create a function to find the last 5 matchups
```{r}

funct.matchups <- function(team, Team2){
  Matchups <- funct.team.sched(team)
  Matchups <- Matchups %>% 
    filter(Opponent == Team2 & !is.na(Result))
  return(Matchups)
}

funct.matchups("CLE", "Boston Celtics")

```

##Create a function to go from name to abbreviation
```{r}
AbrevToName <- function(Abbreviation) {
  if(str_length(Abbreviation) != 3 ) {
    print("You must enter the three letter abbreviation for this team in a string.")
  }
  else {
    
  }
}

```

##Create some functions
```{r}
NBAOdds <- read.csv()

urltable <- "https://widgets.sports-reference.com/wg.fcgi?css=1&site=bbr&url=%2Fteams%2FBOS%2F2018_games.html&div=div_games"

table.s <- htmltab(url)
head(table.s)







find_previous_matchups <- function(Team1, Team2) {
  url <- "https://www.basketball-reference.com/teams/BOS/2018_games.html"
  
  url<-paste0("https://www.basketball-reference.com/teams/", Team1, "/2018_games.html")
  table.sc<-htmltab(url)
  table.sc <- table.sc %>% 
        drop_na() %>%
        filter(Date !="Playoffs")
      names(result)[3]<-"Visitor"
      names(result)[4]<-"PTSV"
      names(result)[5]<-"Home"
      names(result)[6]<-"PTSH"
      result$Date<-as.Date(result$Date, '%a, %b %d, %Y')
      result$PTSH<-as.numeric(result$PTSH)
      result$PTSV<-as.numeric(result$PTSV)
      return(result)
}

schedule_table("2017")
#schedule

schedule_url<-"https://widgets.sports-reference.com/wg.fcgi?css=1&site=bbr&url=%2Fleagues%2FNBA_"

#schedule
schedule_table<-function(year){
  if(year>2018){
    print("The season doesn't start")
  }else if(year<2001){
    print("The season isn't included")
  }else{
    if(year==2012){
      month=c("december","january","february",
              "march","april","may","june")
    }else{
      month=c("october","november","december","january","february",
              "march","april","may","june")
      result=NA
      #Combine the schedule of each month
      for(a in 1:length(month)){
        url<-paste0(schedule_url,year,"_games-",month[a],".html&div=div_schedule")
        table<-htmltab(url)
        result=rbind(result,table)}
      #Clean up the table
      result<-result %>% 
        drop_na() %>%
        filter(Date !="Playoffs")
      names(result)[3]<-"Visitor"
      names(result)[4]<-"PTSV"
      names(result)[5]<-"Home"
      names(result)[6]<-"PTSH"
      result$Date<-as.Date(result$Date, '%a, %b %d, %Y')
      result$PTSH<-as.numeric(result$PTSH)
      result$PTSV<-as.numeric(result$PTSV)
      return(result)
    }
  }
}

```

##Spreads Tables
```{r}

url <-  "http://www.donbest.com/nba/odds/spreads/20171212.html"

SpreadsTable <- url %>%
    read_html %>%
    html_nodes(xpath = '//*[@id="oddsHolder"]/div[1]/table') %>%
    html_table(header = F, fill =T) %>%
    data.frame() %>%
    tbl_df()

head(SpreadsTable)
SpreadsTable <- SpreadsTable[-1, ]

names(SpreadsTable) <- SpreadsTable[1,]
SpreadsTable <- SpreadsTable[-1, ]

SpreadsTable <- SpreadsTable %>% 
  select(Rot, Opener, Team, Time, Bovada, Pinnacle, Mirage)

#Rot works
SpreadsTable <- SpreadsTable %>% 
  mutate(Rot1 = as.character(Rot),
         Rot2 = as.character(Rot))

SpreadsTable$Rot1 <- str_sub(SpreadsTable$Rot1, 1, 3)
SpreadsTable$Rot2 <- str_sub(SpreadsTable$Rot2, 4, 6)

#We need to create a regex pattern
SpreadsTable <- SpreadsTable %>% 
  mutate(OS = Opener)

#Opening Spread
pattern <- str_c("[+-]", "[:digit:]+", ".?", "[:digit:]*","[\\s]")
SpreadsTable$OSAway <- str_match(SpreadsTable$OS, pattern)
SpreadsTable$OSAway <- sub("\\s+", "", SpreadsTable$OSAway)

SpreadsTable$Bovada <- str_match(SpreadsTable$Bovada, pattern)
SpreadsTable$Bovada <- sub("\\s+", "", SpreadsTable$Bovada)

SpreadsTable$Pinnacle <- str_match(SpreadsTable$Pinnacle, pattern)
SpreadsTable$Pinnacle <- sub("\\s+", "", SpreadsTable$Pinnacle)

SpreadsTable$Mirage <- str_match(SpreadsTable$Mirage, pattern)
SpreadsTable$Mirage <- sub("\\s+", "", SpreadsTable$Mirage)

#Teams

#Team Away City
patternteam <- str_c("((^[:upper:][:lower:]+)[:blank:][:upper:][:lower:]+[:blank:])|((^[:upper:][:lower:]+)[:blank:])|((^[:upper:][:lower:]+)[:blank:])")
SpreadsTable$TeamAwayCity <- str_match(SpreadsTable$Team, patternteam)
SpreadsTable$Team <- str_replace(SpreadsTable$Team, patternteam, "")

#Team Away
patternteam2 <- str_c("(^[:upper:][:lower:]+|76ers)")
SpreadsTable$TeamAway <- str_match(SpreadsTable$Team, patternteam2)
SpreadsTable$Team <- str_replace(SpreadsTable$Team, patternteam2, "")

#Put the city and nickname together
SpreadsTable <- as.data.frame(SpreadsTable)
SpreadsTable$Bovada <- SpreadsTable$Bovada[,1]
SpreadsTable$Mirage <- SpreadsTable$Mirage[,1]
SpreadsTable$Pinnacle <- SpreadsTable$Pinnacle[,1]
SpreadsTable$OSAway <- SpreadsTable$OSAway[,1]
SpreadsTable$TeamAwayCity <- SpreadsTable$TeamAwayCity[,1]
SpreadsTable$TeamAway <- SpreadsTable$TeamAway[,1]

SpreadsTable <- SpreadsTable %>% 
  mutate(Away = paste0(TeamAwayCity, TeamAway))

SpreadsTable <- SpreadsTable %>% 
  select(Team, Time, Bovada, Pinnacle, Mirage, Rot1, Rot2, OSAway, Away) %>% 
  dplyr::rename(Home = Team, RotAway = Rot1, RotHome = Rot2)
```

##MoneyLine Tables
```{r}
url <-  "http://www.donbest.com/nba/odds/money-lines/20171206.html"

MoneyLineTable <- url %>%
    read_html %>%
    html_nodes(xpath = '//*[@id="oddsHolder"]/div[1]/table') %>%
    html_table(header = F, fill =T) %>%
    data.frame() %>%
    tbl_df()

head(MoneyLineTable)


MoneyLineTable <- MoneyLineTable[-1, ]

names(MoneyLineTable) <- MoneyLineTable[1,]
MoneyLineTable <- MoneyLineTable[-1, ]

MoneyLineTable <- MoneyLineTable %>% 
  select(Rot, Opener, Team, Time, Bovada, Pinnacle, Mirage)

#Rot works
MoneyLineTable <- MoneyLineTable %>% 
  mutate(Rot1 = as.character(Rot),
         Rot2 = as.character(Rot))

MoneyLineTable$Rot1 <- str_sub(MoneyLineTable$Rot1, 1, 3)
MoneyLineTable$Rot2 <- str_sub(MoneyLineTable$Rot2, 4, 6)

#Money Line Away
pattern <- str_c("^[+-]", "[:digit:]+")
MoneyLineTable$OpenerAwayML <- str_match(MoneyLineTable$Opener, pattern)
MoneyLineTable$BovadaAwayML <- str_match(MoneyLineTable$Bovada, pattern)
MoneyLineTable$PinnacleAwayML <- str_match(MoneyLineTable$Pinnacle, pattern)
MoneyLineTable$MirageAwayML <- str_match(MoneyLineTable$Mirage, pattern)

#Money Line Home
pattern <- str_c("[+-]", "[:digit:]+$")
MoneyLineTable$OpenerHomeML <- str_match(MoneyLineTable$Opener, pattern)
MoneyLineTable$BovadaHomeML <- str_match(MoneyLineTable$Bovada, pattern)
MoneyLineTable$PinnacleHomeML <- str_match(MoneyLineTable$Pinnacle, pattern)
MoneyLineTable$MirageHomeML <- str_match(MoneyLineTable$Mirage, pattern)

#Teams
#Team Away City
patternteam <- str_c("((^[:upper:][:lower:]+)[:blank:][:upper:][:lower:]+[:blank:])|((^[:upper:][:lower:]+)[:blank:])")
MoneyLineTable$TeamAwayCity <- str_match(MoneyLineTable$Team, patternteam)
MoneyLineTable$Team <- str_replace(MoneyLineTable$Team, patternteam, "")

#Team Away
patternteam2 <- str_c("(^[:upper:][:lower:]+|76ers)")
MoneyLineTable$TeamAway <- str_match(MoneyLineTable$Team, patternteam2)
MoneyLineTable$Team <- str_replace(MoneyLineTable$Team, patternteam2, "")

#Put the city and nickname together
MoneyLineTable <- as.data.frame(MoneyLineTable)
#Weird Structure

MoneyLineTable$BovadaAwayML <- MoneyLineTable$BovadaAwayML[,1]
MoneyLineTable$MirageAwayML <- MoneyLineTable$MirageAwayML[,1]
MoneyLineTable$PinnacleAwayML <- MoneyLineTable$PinnacleAwayML[,1]
MoneyLineTable$OpenerAwayML <- MoneyLineTable$OpenerAwayML[,1]
MoneyLineTable$OpenerHomeML <- MoneyLineTable$OpenerHomeML[,1]
MoneyLineTable$PinnacleHomeML <- MoneyLineTable$PinnacleHomeML[,1]
MoneyLineTable$MirageHomeML <- MoneyLineTable$MirageHomeML[,1]
MoneyLineTable$BovadaHomeML <- MoneyLineTable$BovadaHomeML[,1]

#Team 
MoneyLineTable$TeamAwayCity <- MoneyLineTable$TeamAwayCity[,1]
MoneyLineTable$TeamAway <- MoneyLineTable$TeamAway[,1]

MoneyLineTable <- MoneyLineTable %>% 
  mutate(Away = paste0(TeamAwayCity, TeamAway))

MoneyLineTable <- MoneyLineTable %>% 
  select(-Rot, -Opener, -Bovada, - Pinnacle, - Mirage, - TeamAwayCity, -TeamAway) %>% 
  dplyr::rename(Home = Team, RotAway = Rot1, RotHome = Rot2)

head(MoneyLineTable)
```

##Over Under 
```{r}
url <- "http://www.donbest.com/nba/odds/totals/20171206.html"

OverUnderTable <- url %>%
    read_html %>%
    html_nodes(xpath = '//*[@id="oddsHolder"]/div[1]/table') %>%
    html_table(header = F, fill =T) %>%
    data.frame() %>%
    tbl_df()

head(OverUnderTable)


OverUnderTable <- OverUnderTable[-1, ]

names(OverUnderTable) <- OverUnderTable[1,]
OverUnderTable <- OverUnderTable[-1, ]

OverUnderTable <- OverUnderTable %>% 
  select(Rot, Opener, Team, Time, Bovada, Pinnacle, Mirage)

#Rot works
OverUnderTable <- OverUnderTable %>% 
  mutate(Rot1 = as.character(Rot),
         Rot2 = as.character(Rot))

OverUnderTable$Rot1 <- str_sub(OverUnderTable$Rot1, 1, 3)
OverUnderTable$Rot2 <- str_sub(OverUnderTable$Rot2, 4, 6)

#OverUnder
pattern <- str_c("[:digit:]{3}\\.[:digit:]")
OverUnderTable$OpenerOU <- str_match(OverUnderTable$Opener, pattern)
OverUnderTable$BovadaOU <- str_match(OverUnderTable$Bovada, pattern)
OverUnderTable$PinnacleOU <- str_match(OverUnderTable$Pinnacle, pattern)
OverUnderTable$MirageOU <- str_match(OverUnderTable$Mirage, pattern)

#Teams
#Team Away City
patternteam <- str_c("((^[:upper:][:lower:]+)[:blank:][:upper:][:lower:]+[:blank:])|((^[:upper:][:lower:]+)[:blank:])")
OverUnderTable$TeamAwayCity <- str_match(OverUnderTable$Team, patternteam)
OverUnderTable$Team <- str_replace(OverUnderTable$Team, patternteam, "")

#Team Away
patternteam2 <- str_c("(^[:upper:][:lower:]+|76ers)")
OverUnderTable$TeamAway <- str_match(OverUnderTable$Team, patternteam2)
OverUnderTable$Team <- str_replace(OverUnderTable$Team, patternteam2, "")

#Put the city and nickname together
OverUnderTable <- as.data.frame(OverUnderTable)
#Weird Structure


OverUnderTable$BovadaOU <- OverUnderTable$BovadaOU[,1]
OverUnderTable$MirageOU <- OverUnderTable$MirageOU[,1]
OverUnderTable$PinnacleOU <- OverUnderTable$PinnacleOU[,1]
OverUnderTable$OpenerOU <- OverUnderTable$OpenerOU[,1]

#Team 
OverUnderTable$TeamAwayCity <- OverUnderTable$TeamAwayCity[,1]
OverUnderTable$TeamAway <- OverUnderTable$TeamAway[,1]

OverUnderTable <- OverUnderTable %>% 
  mutate(Away = paste0(TeamAwayCity, TeamAway))

OverUnderTable <- OverUnderTable %>% 
  select(-Rot, -Opener, -Bovada, - Pinnacle, - Mirage, - TeamAwayCity, -TeamAway) %>% 
  dplyr::rename(Home = Team, RotAway = Rot1, RotHome = Rot2)

head(OverUnderTable)

```

##Bind the individual tables together.
```{r}
head(SpreadsTable)
head(MoneyLineTable)
head(OverUnderTable)

BettingTable <- left_join(SpreadsTable, MoneyLineTable, by = c("Home", "Away", "Time", "RotAway", "RotHome")) %>% 
  left_join(OverUnderTable, by = c("Home", "Away", "Time", "RotAway", "RotHome"))

BettingTable <- BettingTable[, c(1, 9, 2:8, 10:21)] %>% 
  dplyr::rename(BovadaAwayS = Bovada,
         PinnacleAwayS = Pinnacle,
         MirageAwayS = Mirage,
         OpenerAwayS = OSAway)

BettingTable <- BettingTable %>% 
  mutate(Time = hm(Time))

for(i in 4:length(BettingTable)){
  BettingTable[,i] <- as.numeric(BettingTable[,i]) 
}

#Create a win probability from the Bovada money line
BettingTable <- BettingTable %>% 
  mutate(WP.HB = ifelse(BovadaHomeML > 0, 100/(BovadaHomeML + 100),
                       BovadaHomeML/(BovadaHomeML -100)),
         WP.VB = ifelse(BovadaAwayML > 0, 100/(BovadaAwayML + 100),
                       BovadaAwayML/(BovadaAwayML -100)),
         WP.H = (WP.HB + (1-WP.VB))/2,
         WP.V = 1 - WP.H)  %>% 
  select(-WP.HB, -WP.VB)


head(BettingTable)
```

