---
title: "NBA-Lisha"
output: html_document
---

#Load Libraries
```{r}
library(rvest)
library(dplyr)
library(pipeR)
library(knitr)
library(stringr)
library(htmltab)
library(tidyr)
library(ggplot2)
library(maps)
library(ggrepel)
```

#htmltab
```{r}
schedule_url<-"https://widgets.sports-reference.com/wg.fcgi?css=1&site=bbr&url=%2Fleagues%2FNBA_"
standing_url<-"https://widgets.sports-reference.com/wg.fcgi?css=1&site=bbr&url=%2Fleagues%2FNBA_"
opgs_url<-"https://widgets.sports-reference.com/wg.fcgi?css=1&site=bbr&url=%2Fplayoffs%2FNBA_"
ops_url<-"https://widgets.sports-reference.com/wg.fcgi?css=1&site=bbr&url=%2Fplayoffs%2FNBA_"


#schedule
schedule_table<-function(year){
  if(year>2018){
    print("The season doesn't start")
  }else if(year<2001){
    print("The season isn't included")
  }else{
    if(year==2012){
    month=c("december","january","february",
          "march","april","may","june")
    }else if(year==2006|year==2005){
    month=c("november","december","january","february",
          "march","april","may","june")
    }else if(year==2018){
      month=c("october","november","december","january","february",
          "march","april")
    }else{
      month=c("october","november","december","january","february",
          "march","april","may","june")
    }
  result=NA
  for(a in 1:length(month)){
    url<-readLines(paste0(schedule_url,year,"_games-",month[a],
                          ".html&div=div_schedule"))
    thepage.tib<-as_tibble(url)
    temp.text<-thepage.tib[104,]
    table<-htmltab(temp.text[[1]], which=1,rm_nodata_cols = F)
    result=rbind(result,table)}
  names(result)[3]<-"Visitor"
  names(result)[4]<-"PTSV"
  names(result)[5]<-"Home"
  names(result)[6]<-"PTSH"
  names(result)[7]<-"Box"
  names(result)[8]<-"OT"
  result<-result %>% 
    filter(Date !="Playoffs")
  result$Date<-as.Date(result$Date, '%a, %b %d, %Y')
  return(result)
    }
  }

schedule_2005<-schedule_table(2005)
schedule_2018<-schedule_table(2018)

a<-left_join(schedule_2017,NBAOdds20072018Update, by=c("Date", "Visitor","Home","PTSH","PTSV"))


#webscape standings for east or west conference and clean it.
webscrape_standings<-function(year){
  url<-readLines(paste0(standing_url,year,
                        '_standings.html&div=div_expanded_standings'))
  thepage.tib<-as_tibble(url)
  temp.text<-thepage.tib[104,]
  table<-htmltab(temp.text[[1]], which=1,rm_nodata_cols = F)
  table<-table[-1]
#  names(table)[1]<-"Team"
#  table$Team<-gsub("[*(0-9)]","",table$Team)
#  table$Team<-sub("\\s+$", "", table$Team)
#  table$Team<-gsub(" ers"," 76ers", table$Team)
  return(table)
}

standings_2017<-webscrape_standings(2017)

#opponent per game stats
opsg_table <- function(year){
  url<-paste0(opgs_url,year,".html&div=div_opponent-stats-per_game")
  table<-htmltab(url)
  return(table)
}

opsg<-opsg_table(2017)[-1]

#opponent shooting
ops_table<-function(year){
  url<-paste0(ops_url,year,".html&div=div_opponent_shooting")
  table<-htmltab(url)
  return(table)
}

ops<-ops_table(2017)[-1]

```

#NBA map
```{r}
schedule_map<-function(date){
usa<-map_data("usa")
usa_map<-ggplot() + 
  geom_polygon(data = usa, aes(x=long, y = lat, group = group), fill = "yellow", color = "blue") + 
  coord_fixed(1.3)

labs <- data.frame(
  long = c(-122.203092,-118.267233,-81.688141,-122.666119,-71.062151,-86.155528,
           -90.050495,-87.917068,-90.079220,-81.399844,-75.172037,-112.070156,
           -84.392168,-87.674089,-121.499845,-74.016235,-96.815228,-83.055133,
           -80.374820,-97.515083,-111.901235,-80.839322,-105.007694,-73.993407,
           -98.437370,-95.362091,-118.267233,-93.275882,-77.020959,-79.426987,
           -90.079220,-122.353806,-74.016235,-90.079220,-80.839235),
  lat = c(37.750427, 34.043169,41.496762, 45.532069, 42.366437,39.764087,
          35.138423,43.043929,29.952573,28.635790,39.901613,33.445462,
          33.757064,41.880867,38.580936,40.659398,32.791563,42.341150,
          25.675423,35.463528,40.768442,35.225210,39.749438,40.750651,
          29.427211,29.750895,34.043169,44.979680,38.898251,43.634139,
          29.952573,47.622216,40.659398,29.952573,35.225668),
  Home = c("Golden State Warriors", "Los Angeles Lakers", "Cleveland Cavaliers", "Portland Trail Blazers","Boston Celtics","Indiana Pacers","Memphis Grizzlies","Milwaukee Bucks","New Orleans Pelicans","Orlando Magic","Philadelphia 76ers","Phoenix Suns","Atlanta Hawks","Chicago Bulls","Sacramento Kings","Brooklyn Nets","Dallas Mavericks","Detroit Pistons","Miami Heat","Oklahoma City Thunder","Utah Jazz","Charlotte Hornets","Denver Nuggets","New York Knicks","San Antonio Spurs","Houston Rockets","Los Angeles Clippers","Minnesota Timberwolves","Washington Wizards","Toronto Raptors","New Orleans Hornets","Seattle SuperSonics","New Jersey Nets","New Orleans/Oklahoma City Hornets","Charlotte Bobcats"),
  stringsAsFactors = FALSE
  ) 
m<-as.numeric(substr(date,6,7))
if(m>9&&m<13){
  today<-schedule_table(as.numeric(substr(date, 1, 4))+1)
}else if(m<7&&m>0){
  today<-schedule_table(as.numeric(substr(date, 1, 4)))
}else{
  return(usa_map)
}
today<-schedule_table(as.numeric(substr(date, 1, 4))+1)
today<-today %>%
  filter(Date==date) %>%
  left_join(labs, by="Home")

map<-usa_map+ 
  geom_point(data = today, aes(x = long, y = lat), color = "black", size = 3) +
  geom_point(data = today, aes(x = long, y = lat), color = "red", size = 2)+
  geom_text_repel(data=today, aes(x=long, y=lat,label = Home),alpha=1,size=3)

return(map)
}

schedule_map("2016-11-21")
```

```{r}
thepage <-  readLines('https://widgets.sports-reference.com/wg.fcgi?css=1&site=bbr&url=%2Fleagues%2FNBA_2016_games-october.html&div=div_schedule')

#Convert the webpage into an easily subsettable tibble
thepage.tib <- as_tibble(thepage) 

#Find the row including the data table
temp.text <- thepage.tib[104,] #This stores as a list

#Read the html code as a data table
AdvancedPBP <- htmltab(temp.text[[1]], which =1 ) #Call the data table element in the list 

schedule_2016<-schedule_2016 %>% 
    drop_na() %>%
    filter(Date !="Playoffs")
```

