---
title: "Betting Odds"
author: "Derrick Yam"
date: "December 6, 2017"
output: html_document
---

##Load Libraries
```{r}
library(rvest)
library(pipeR)
library(knitr)
library(xml2)
library(htmltab)
library(readxl)
library(tidyr)
library(lubridate)
library(dplyr)
library(stringr)
options(tibble.width = Inf)
```


##Betting Odds
Historical Data from https://www.indatabet.com/free.html
Better source: http://www.sportsbookreviewsonline.com/scoresoddsarchives/nba/nbaoddsarchives.htm

##Clean and combine the historical betting odds
```{r}
setwd("C:/Users/dyam/Dropbox (Brown)/Brown/Statistical Programming/r-package-teamivy/Historical Betting Lines")

NBA2018 <- readxl::read_excel("nba odds 2017-18.xlsx")
NBA2017 <- readxl::read_excel("nba odds 2016-17.xlsx")
NBA2016 <- readxl::read_excel("nba odds 2015-16.xlsx")
NBA2015 <- readxl::read_excel("nba odds 2014-15.xlsx")
NBA2014 <- readxl::read_excel("nba odds 2013-14.xlsx")
NBA2013 <- readxl::read_excel("nba odds 2012-13.xlsx")
NBA2012 <- readxl::read_excel("nba odds 2011-12.xlsx")
NBA2011 <- readxl::read_excel("nba odds 2010-11.xlsx")
NBA2010 <- readxl::read_excel("nba odds 2009-10.xlsx")
NBA2009 <- readxl::read_excel("nba odds 2008-09.xlsx")
NBA2008 <- readxl::read_excel("nba odds 2007-08.xlsx")

#Add a year variable to each table
#Then reformat the date
NBA2018 <- NBA2018 %>% 
  mutate(Date = ifelse(Date < 900, paste0(0, as.character(Date), 2018), paste0(as.character(Date), 2017))) %>% 
  mutate(Date = mdy(Date))

NBA2017 <- NBA2017 %>% 
  mutate(Date = ifelse(Date < 900, paste0(0, as.character(Date), 2017), paste0(as.character(Date), 2016))) %>% 
  mutate(Date = mdy(Date))

NBA2016 <- NBA2016 %>% 
  mutate(Date = ifelse(Date < 900, paste0(0, as.character(Date), 2016), paste0(as.character(Date), 2015))) %>% 
  mutate(Date = mdy(Date))

NBA2015 <- NBA2015 %>% 
  mutate(Date = ifelse(Date < 900, paste0(0, as.character(Date), 2015), paste0(as.character(Date), 2014))) %>% 
  mutate(Date = mdy(Date))

NBA2014 <- NBA2014 %>% 
  mutate(Date = ifelse(Date < 900, paste0(0, as.character(Date), 2014), paste0(as.character(Date), 2013))) %>% 
  mutate(Date = mdy(Date))

NBA2013 <- NBA2013 %>% 
  mutate(Date = ifelse(Date < 900, paste0(0, as.character(Date), 2013), paste0(as.character(Date), 2012))) %>% 
  mutate(Date = mdy(Date))

NBA2012 <- NBA2012 %>% 
  mutate(Date = ifelse(Date < 900, paste0(0, as.character(Date), 2012), paste0(as.character(Date), 2011))) %>% 
  mutate(Date = mdy(Date))

NBA2011 <- NBA2011 %>% 
  mutate(Date = ifelse(Date < 900, paste0(0, as.character(Date), 2011), paste0(as.character(Date), 2010))) %>% 
  mutate(Date = mdy(Date))

NBA2010 <- NBA2010 %>% 
  mutate(Date = ifelse(Date < 900, paste0(0, as.character(Date), 2010), paste0(as.character(Date), 2009))) %>% 
  mutate(Date = mdy(Date))

NBA2009 <- NBA2009 %>% 
  mutate(Date = ifelse(Date < 900, paste0(0, as.character(Date), 2009), paste0(as.character(Date), 2008))) %>% 
  mutate(Date = mdy(Date))

NBA2008 <- NBA2008 %>% 
  mutate(Date = ifelse(Date < 900, paste0(0, as.character(Date), 2008), paste0(as.character(Date), 2007))) %>% 
  mutate(Date = mdy(Date))

#Combine the different years
NBALines <- rbind(NBA2018, NBA2017, NBA2016, NBA2015, NBA2014,
                      NBA2013, NBA2012, NBA2011, NBA2010, NBA2009, NBA2008)
```


#Spread the two visitor home rows into one row per game
```{r}

head(NBALines)
NBAHome <- NBALines %>% 
  filter(VH == "H")
NBAVis <- NBALines %>% 
  filter(VH == "V")
NBANeutral <- NBALines %>% 
  filter(VH == "N")

head(NBANeutral)

temp <- NBANeutral %>% 
  group_by(Date) %>% 
  slice(1)

NBAHome <- bind_rows(NBAHome, temp)

temp2 <- NBANeutral %>% 
  group_by(Date) %>% 
  slice(2)

NBAVis <- bind_rows(NBAVis, temp2)

NBAOdds <- bind_cols(NBAHome, NBAVis)

NBAOdds <- NBAOdds %>% 
  rename(VH = VH, Date1 = Date1, VH1 = VH1)

head(NBAOdds)
```


#Some discrepancies with the dates
```{r}
NBAOdds %>% filter(Date != Date1)
NBAOdds$Date[NBAOdds$Date == "2009-01-10" & NBAOdds$Team == "Phoenix"] <- "2009-01-09"
NBAOdds$Date[NBAOdds$Date == "2011-01-30" & NBAOdds$Team == "LAClippers"] <- "2011-01-29"

NBAOdds <- NBAOdds %>% 
  select(-VH, -Date1, -VH1, -`2H`, -`2H1`)

##Rename Variables
names(NBAOdds) <- c("Date", "RotH", "Home", "HQ1","HQ2","HQ3","HQ4","HFinal","OpenSpread",
                    "CloseSpread", "MoneyLineHome", "RotV", "Away",  "VQ1",   "VQ2",   "VQ3",   "VQ4",
                    "VFinal", "OpenOverUnder",  "CloseOverUnder", "MoneyLineVisitor")

head(NBAOdds)
```

#Sometimes the spread and over under are switched we need to fix this.

```{r}
#Also all the numbers have some issues, we must individually fix all of them which will be a major pain.
#Turn all the pickems into a spread of 0
NBAOdds <- NBAOdds %>% 
  mutate(OpenSpread = ifelse(OpenSpread == "pk", 0, OpenSpread),
         CloseSpread = ifelse(CloseSpread == "pk", 0, CloseSpread),
         OpenOverUnder = ifelse(OpenOverUnder == "pk", 0, OpenOverUnder),
         CloseOverUnder = ifelse(CloseOverUnder == "pk", 0, CloseOverUnder))

#Start with the Open Spread
table(NBAOdds$OpenSpread)
##Theres definily some issues with the numbers, let's just get them all into numeric first.
NBAOdds$OpenSpread[NBAOdds$OpenSpread == "5-126"] <- 5
NBAOdds$OpenSpread[NBAOdds$OpenSpread == "4.5049999999999999"] <- 4.5
NBAOdds$OpenSpread[NBAOdds$OpenSpread == "3-109"] <- 3
NBAOdds$OpenSpread[NBAOdds$OpenSpread == "5.5049999999999999"] <- 5.5
NBAOdds$OpenSpread[NBAOdds$OpenSpread == "213.5o-126"] <- 213.5
NBAOdds$OpenSpread[NBAOdds$OpenSpread == "4.5049999999999999"] <- 4.5
NBAOdds$OpenSpread[NBAOdds$OpenSpread == "4.5049999999999999"] <- 4.5

NBAOdds <- NBAOdds %>% 
  mutate(OpenSpread = as.numeric(as.character(OpenSpread)))

#Close Spread         
table(NBAOdds$CloseSpread)

NBAOdds <- NBAOdds %>% 
  mutate(CloseSpread = as.numeric(as.character(CloseSpread)))

#OpenOverUnder
table(NBAOdds$OpenOverUnder)
NBAOdds$OpenOverUnder[NBAOdds$OpenOverUnder == "8-115"] <- 8
NBAOdds$OpenOverUnder[NBAOdds$OpenOverUnder == "5-115"] <- 5
NBAOdds$OpenOverUnder[NBAOdds$OpenOverUnder == "197.5u10"] <- 197.5
NBAOdds$OpenOverUnder[NBAOdds$OpenOverUnder == "10+104"] <- 10
NBAOdds$OpenOverUnder[NBAOdds$OpenOverUnder == "1955.5"] <- 195.5

NBAOdds <- NBAOdds %>% 
  mutate(OpenOverUnder = as.numeric(as.character(OpenOverUnder)))

#CloseOverUnder
table(NBAOdds$CloseOverUnder)
NBAOdds <- NBAOdds %>% 
  mutate(CloseOverUnder = as.numeric(as.character(CloseOverUnder)))

#Check Tables Again
table(NBAOdds$OpenSpread)
#43.5 to 114 don't seem right
NBAOdds$OpenSpread[NBAOdds$OpenSpread == 605] <- 6.5
table(NBAOdds$CloseSpread) #Nothing between 25 and 170.5 Good
table(NBAOdds$OpenOverUnder)
NBAOdds$OpenOverUnder[NBAOdds$OpenOverUnder == 505] <- 5.5 #Again, 45.5 to 109 don't seem right

table(NBAOdds$CloseOverUnder) #Should be good here

##For simplicity sake all the weird range open values make them the close values
NBAOdds <- NBAOdds %>% 
  mutate(OpenSpread= ifelse(OpenSpread >= 43.5 & OpenSpread <= 114, CloseSpread, OpenSpread))
table(NBAOdds$OpenSpread)

NBAOdds <- NBAOdds %>% 
  mutate(OpenOverUnder= ifelse(OpenOverUnder >= 45.5 & OpenOverUnder <= 109, CloseOverUnder, OpenOverUnder))
table(NBAOdds$OpenOverUnder)

#Now swap the OU and spread when they are clearly not right
NBAOdds <- NBAOdds %>% 
  mutate(OS = ifelse(OpenSpread > OpenOverUnder, OpenOverUnder, OpenSpread),
         OOU = ifelse(OpenOverUnder < OpenSpread, OpenSpread, OpenOverUnder),
         CS = ifelse(CloseSpread > CloseOverUnder, CloseOverUnder, CloseSpread),
         COU = ifelse(CloseOverUnder < CloseSpread, CloseSpread, CloseOverUnder))

#Check if that worked
head(NBAOdds)
```

#Yes! Now remove the old variables
```{r}

NBAOdds <- NBAOdds %>% 
  select(-OpenSpread, -OpenOverUnder, -CloseSpread, -CloseOverUnder)

#Edit the money line variable
table(NBAOdds$MoneyLineHome)
NBAOdds$MoneyLineHome[NBAOdds$MoneyLineHome == "NL"] <- NA
NBAOdds <- NBAOdds %>% 
  mutate(MoneyLineHome = as.numeric(as.character(MoneyLineHome)))

table(NBAOdds$MoneyLineVisitor)
NBAOdds$MoneyLineVisitor[NBAOdds$MoneyLineVisitor == "NL"] <- NA
NBAOdds <- NBAOdds %>% 
  mutate(MoneyLineVisitor = as.numeric(as.character(MoneyLineVisitor)))

#Create a win probability from the money line
NBAOdds <- NBAOdds %>% 
  mutate(WP.H2 = ifelse(MoneyLineHome > 0, 100/(MoneyLineHome + 100),
                       MoneyLineHome/(MoneyLineHome -100)),
         WP.V2 = ifelse(MoneyLineVisitor > 0, 100/(MoneyLineVisitor + 100),
                       MoneyLineVisitor/(MoneyLineVisitor -100)),
         WP.H = (WP.H2 + (1-WP.V2))/2,
         WP.V = 1 - WP.H)

NBAOdds <- NBAOdds %>% 
  select(-WP.H2, -WP.V2)

#Create new over under and points total variable
NBAOdds <- NBAOdds %>% 
  mutate(FinalOU = ifelse(HFinal + VFinal > COU, "Over", "Under"),
         PointsTotal = HFinal + VFinal)

head(NBAOdds)

#Create new covered spread variable
NBAOdds <- NBAOdds %>% 
  mutate(SpreadH = ifelse(MoneyLineHome < 0, -CS, CS))

NBAOdds <- NBAOdds %>% 
  mutate(Covered = ifelse(HFinal + SpreadH - VFinal > 0, 1, 0))

##The team names were edited in Excel
#write.csv(NBAOdds, "NBAOdds20072018.csv")
```

