---
title: "NBA Team Analysis Package"
author: "Teresa DeAtley"
date: "November 29, 2017"
output: html_document
---
```{r}
library(rvest)
library(dplyr)
#library(pipeR)javascript:;
library(magrittr)
library(knitr)
install.packages("htmltab")
library(htmltab)
```

---
title: "NBA Team Analysis Package"
author: "Teresa DeAtley"
date: "November 29, 2017"
output: html_document
---
```{r}
library(rvest)
library(dplyr)
#library(pipeR)javascript:;
library(magrittr)
library(knitr)
install.packages("htmltab")
library(htmltab)
library(tibble)
```
```{r}

Rosterpage<-  readLines('https://widgets.sports-reference.com/wg.fcgi?css=1&site=bbr&url=%2Fteams%2FBOS%2F2018.html&div=div_advanced')

#Convert the webpage into an easily subsettable tibble
thepage.tib <- as.tibble(Rosterpage) 

#Find the row including the data table
temp.text <- thepage.tib[104,] #This stores as a list

#Read the html code as a data table
Roster<- htmltab(temp.text[[1]], which =1 ) #Call the data table element in the list 

#Format the data table
Roster <- Roster %>% 
  mutate(Team = "BOS") %>% 
  rename(Player = V1) %>% 
  dplyr::select(-Rk)

head(Roster)


```
#tibble Rosterpage
```{r}
Rosterpage<-  readLines('https://widgets.sports-reference.com/wg.fcgi?css=1&site=bbr&url=%2Fteams%2FBOS%2F2018.html&div=div_advanced')

#Convert the webpage into an easily subsettable tibble
thepage.tib <- as.tibble(Rosterpage) 

#Find the row including the data table
temp.text <- thepage.tib[104,] #This stores as a list

#Read the html code as a data table
Roster<- htmltab(temp.text[[1]], which =1 ) #Call the data table element in the list 

#Format the data table
Roster <- Roster %>% 
  mutate(Team = "BOS") %>% 
  rename(Player = V1) %>% 
  dplyr::select(-Rk)

head(Roster)

funct.roster <- function(team, year){
  urltable <- paste0("https://widgets.sports-reference.com/wg.fcgi?css=1&site=bbr&url=%2Fteams%2F",team, "%2F", year, ".html&div=div_per_game")
  
Rosterpage <- readLines(urltable)

#Convert the webpage into an easily subsettable tibble
thepage.tib <- as.tibble(Rosterpage) 

#Find the row including the data table
temp.text <- thepage.tib[104,] #This stores as a list

#Read the html code as a data table
Roster<- htmltab(temp.text[[1]], which =1 ) #Call the data table element in the list 

Roster <- Roster %>% 
  mutate(Team = "BOS") %>% 
  rename(Player = V1) %>% 
  dplyr::select(-Rk)
return(Roster)
}

Roster <-funct.roster("BOS", "2017")


```

#New per-game
```{r}
Pergamepage<-  readLines('https://widgets.sports-reference.com/wg.fcgi?css=1&site=bbr&url=%2Fteams%2FBOS%2F2018.html&div=div_per_game')

#Convert the webpage into an easily subsettable tibble
thepage.tib <- as.tibble(Pergamepage) 

#Find the row including the data table
temp.text <- thepage.tib[104,] #This stores as a list

#Read the html code as a data table
Pergamepage<- htmltab(temp.text[[1]], which =1 ) #Call the data table element in the list 

#Format the data table
Pergamepage <- Pergamepage %>% 
  mutate(Team = "BOS") %>% 
  rename(Player = V1) %>% 
  dplyr::select(-Rk)

head(Pergamepage)


funct.pergame <- function(team, year){
  urltable <- paste0("https://widgets.sports-reference.com/wg.fcgi?css=1&site=bbr&url=%2Fteams%2F",team, "%2F", year, ".html&div=div_per_game")
  
Pergamepage <- readLines(urltable)

#Convert the webpage into an easily subsettable tibble
thepage.tib <- as.tibble(Pergamepage) 

#Find the row including the data table
temp.text <- thepage.tib[104,] #This stores as a list

#Read the html code as a data table
Pergamepage<- htmltab(temp.text[[1]], which =1 ) #Call the data table element in the list 

Pergamepage <- Pergamepage%>% 
  mutate(Team = "BOS") %>% 
  rename(Player = V1) %>% 
  dplyr::select(-Rk)
return(Roster)
}

Pergamepage <-funct.pergame("BOS", "2017")
```



